Selim
mrbrooks06/amazonProject pull request #6
Opened 2021-06-23 23:23 UTC by selimcim

2021-06-23 23:27 UTC, SAkkaya requested changes

2021-06-23 23:27 UTC, SAkkaya commented on src/test/java/Test/vacuum_cleaner.java
> +
after method ekleyebiliriz eline saglik

2021-06-23 23:28 UTC, selimcim commented on src/test/java/Test/vacuum_cleaner.java
> +
after method var abi

2021-06-23 23:28 UTC, Baros2535 commented on src/test/java/Test/vacuum_cleaner.java
> +
abi varmış

2021-06-23 23:28 UTC, SAkkaya commented on src/test/java/Test/vacuum_cleaner.java
> +
tamam kabul ediyorum.

2021-06-23 23:29 UTC, Baros2535 commented on src/test/java/Test/vacuum_cleaner.java
> +
teşekkürler abi çok güzel merge edeceğim

2021-06-23 23:29 UTC, HACIARPACI commented on src/test/java/Test/vacuum_cleaner.java
> +
mükemmelll

2021-06-23 23:33 UTC, SAkkaya approved these changes

2021-06-24 13:11 UTC, SAkkaya commented
super devam edebilirsin

2021-06-24 13:11 UTC, merged